# Generated by Django 5.0.2 on 2024-04-08 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_exteriors_second_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kitchens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("KitchenName", models.CharField(max_length=100)),
                ("main_image", models.ImageField(upload_to="kitchens/")),
                ("location", models.CharField(max_length=50)),
                ("completion_year", models.PositiveIntegerField()),
                ("timeline", models.CharField(max_length=15)),
                ("about", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="KitchenImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="kitchen_images/")),
                (
                    "description",
                    models.CharField(default="Your default value here", max_length=255),
                ),
                (
                    "kitchen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.kitchens"
                    ),
                ),
            ],
        ),
    ]
