# Generated by Django 5.0.2 on 2024-04-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_privatehouses_privatehouseimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exteriors",
            old_name="InteriorName",
            new_name="ExteriorName",
        ),
    ]
