# Generated by Django 5.0.2 on 2024-04-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_rename_interiorname_exteriors_exteriorname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exteriors",
            old_name="timline",
            new_name="timeline",
        ),
    ]
